update fair use policy
fiskaltrust/productdescription-de-doc pull request #163
Opened 2021-04-13 12:40 UTC by christian-rogobete

2021-04-14 11:15 UTC, steininger requested changes

2021-04-14 11:15 UTC, steininger commented on product-service-description/market-de-fair-use-policy.md
> +Eine aktive Queue ist eine im Einsatz befindliche Queue, die ein elektronisches Aufzeichnungssystem (GoBD Kasse inkl. angeschlossene Eingabegeräte) repräsentiert.
Bin mir nicht sicher ob "im Einsatz" befindlich richtig ist. Im Lebenszyklus der Queue ist aktiv zwischen dem Inbetriebnahmebeleg und Außerbetriebnahmebeleg. Theoretisch kann sie auch im Einsatz sein, bevor der Inbetriebnahmebeleg gesendet wird.

2021-04-14 11:15 UTC, steininger commented on product-service-description/market-de-fair-use-policy.md
> +Eine aktive Queue ist eine im Einsatz befindliche Queue, die ein elektronisches Aufzeichnungssystem (GoBD Kasse inkl. angeschlossene Eingabegeräte) repräsentiert.
"GoBD Kasse" würde ich nicht so schreiben. In den BMF FAQ wird es "Aufzeichnungssystem" genannt: https://www.bundesfinanzministerium.de/Content/DE/FAQ/2020-02-18-steuergerechtigkeit-belegpflicht.html#doc0926b642-b4d2-41cb-8fac-90bbf815fcbcbodyText5

2021-04-14 11:15 UTC, steininger commented on product-service-description/market-de-fair-use-policy.md
> +### Terminals
In relation zur KassenSichV würd ich hier auch auf die Definition des "Aufzeichnungssystem" verweisen.
In relation zum fiskaltrust Interface geht es um die "TerminalID".

2021-04-14 11:15 UTC, steininger commented on product-service-description/market-de-fair-use-policy.md
> +Standortbezogene Produkte sind Produkte, die von allen aktiven Queues eines Outlets gemeinsam verwendet werden können. Z.B. Sorglos Bundles. Diese Produkte werden pro Outlet erworben.
Ich würd die Reihenfolge ändern.
Standortbezogene Produkte, sind Produkte (oder besser Subscriptions) welche pro Outlet erworben werden und nehmen daher Einfluss auf die dem Outlet untergeordneten Aufzeichnungssysteme (Queues) und technischen Sicherheitseinrichtungen (TSE / SCU)

2021-04-14 11:15 UTC, steininger commented on product-service-description/market-de-fair-use-policy.md
> +Diese Fair Use Regeln können durch spezifische Eigenschaften einzelner standortbezogener Produkte weiter eingeschränkt werden. Achten Sie deshalb bitte auch auf die konkreten Produktmerkmale.
Wollen wir es "nur" bei einteschränkt lassen. Ich denk positiver wäre "verändert werden".

2021-04-14 11:15 UTC, steininger commented on product-service-description/market-de-fair-use-policy.md
> +Bei Nichteinhaltung der Fair Use Policy behält sich die fiskaltrust gmbh das Recht vor, den Betrieb der im betroffenen Outlet verwendeten Produkte und Komponenten, nach erfolgloser Mahnung einzustell
Das Thema "nach erfolglose Mahnung" ist technisch nicht wirklich abbildbar denk ich. 
Nachdem es Fair-Use pro Monat ist, würde ich eher zu folgender Formulierung neigen: "..., den Betrieb der im betroffenen Outlet verwendeten Produkte und Komponenten einzuschränke, bis sie diese wieder innerhalb des Fair-Use-Rahmen befinden". 
Am Monatsersten passiert das ja eigentlich automatisch .....

2021-04-14 11:15 UTC, steininger commented on product-service-description/market-de-fair-use-policy.md
> +Bei Fragen und Anregungen im Zusammenhang mit dieser Fair Use Policy wenden Sie sich bitte an [info@fiskaltrust.de](mailto:info@fiskaltrust.de).
sollte hier nicht support@fiskaltrust.de hin

2021-04-14 11:15 UTC, steininger commented on product-service-description/market-de-fair-use-policy.md
>  [PDF Download der Fair Use Policy](media/market-de-fair-use-policy.pdf)
das sollte hinter einen perma-link

2021-04-15 07:28 UTC, christian-rogobete commented on product-service-description/market-de-fair-use-policy.md
> +Eine aktive Queue ist eine im Einsatz befindliche Queue, die ein elektronisches Aufzeichnungssystem (GoBD Kasse inkl. angeschlossene Eingabegeräte) repräsentiert.
verbessert

2021-04-15 07:28 UTC, christian-rogobete commented on product-service-description/market-de-fair-use-policy.md
> +Eine aktive Queue ist eine im Einsatz befindliche Queue, die ein elektronisches Aufzeichnungssystem (GoBD Kasse inkl. angeschlossene Eingabegeräte) repräsentiert.
verbessert

2021-04-15 07:28 UTC, christian-rogobete commented on product-service-description/market-de-fair-use-policy.md
> +### Terminals
verbessert

2021-04-15 07:28 UTC, christian-rogobete commented on product-service-description/market-de-fair-use-policy.md
> +Standortbezogene Produkte sind Produkte, die von allen aktiven Queues eines Outlets gemeinsam verwendet werden können. Z.B. Sorglos Bundles. Diese Produkte werden pro Outlet erworben.
verbessert

2021-04-15 07:28 UTC, christian-rogobete commented on product-service-description/market-de-fair-use-policy.md
> +Diese Fair Use Regeln können durch spezifische Eigenschaften einzelner standortbezogener Produkte weiter eingeschränkt werden. Achten Sie deshalb bitte auch auf die konkreten Produktmerkmale.
verbessert

2021-04-15 07:28 UTC, christian-rogobete commented on product-service-description/market-de-fair-use-policy.md
> +Bei Nichteinhaltung der Fair Use Policy behält sich die fiskaltrust gmbh das Recht vor, den Betrieb der im betroffenen Outlet verwendeten Produkte und Komponenten, nach erfolgloser Mahnung einzustell
verbessert

2021-04-15 07:28 UTC, christian-rogobete commented on product-service-description/market-de-fair-use-policy.md
> +Bei Fragen und Anregungen im Zusammenhang mit dieser Fair Use Policy wenden Sie sich bitte an [info@fiskaltrust.de](mailto:info@fiskaltrust.de).
verbessert

2021-04-15 07:29 UTC, christian-rogobete commented on product-service-description/market-de-fair-use-policy.md
>  [PDF Download der Fair Use Policy](media/market-de-fair-use-policy.pdf)
hier kein permalink da es die origin ist

2021-04-21 08:01 UTC, merged